### PR TITLE
feat(tests): Add comprehensive test suite for TidesDB.

### LINKED ISSUE #4: Python test suite
Unit testing classes accordingly.

### PR DESCRIPTION
**Pull request by imprvhub**
Closes #4

This adds a complete test suite covering all major functionality:

* test_tidesdb.py: Tests basic operations (open/close)
* test_data_operations.py: Tests CRUD operations (put/get/delete) and compaction
* test_cursor.py: Tests bi-directional data iteration
* test_transaction.py: Tests transactional operations (commit/rollback)

Additional changes:
- Added mock implementation for testing without DB installation
- Updated requirements.txt with latest pytest (>=8.3.4) and pytest-cov (>=6.0.0)
- Test coverage at 75%

### CODE REVIEW

**Comment by guycipher** [comment]
Hi @imprvhub I am reviewing.

**Comment by imprvhub** [comment]
Outputs after commands:
1. `pytest --cov=tests.mock_tidesdb tests/ --cov-report term-missing`
Captura de pantalla 2024-12-19 a la(s) 17 12 56

2.` python -m unittest discover tests -v`

Captura de pantalla 2024-12-19 a la(s) 17 18 36

What do you think? If you need some adjustments just let me know! 👍

**Comment by guycipher** [comment]
This looks very good @imprvhub.  Great job.  One thing I noticed is you may be using an older version of TidesDB possibly as you cannot set the data structure here which is part of the create column family method.  Again this is minor and can be updated.

**Comment by guycipher** [comment]
I approve!  Great job again.

**Pull request merged**
